@startuml
(*) --> "填写请假单，提出请假申请"
-->"项目经理审批"
If "审批" then
    -->[不同意](*)
Else
    -->[同意] "是否大于3天"
    If "比较" then
        -->[Yes]"部门经理审核"
        -->(*)
    Else
        -->[No](*)
    Endif
Endif
@enduml